#!/bin/bash
# This script sets up the environment for the Horizon CS Daybook Uploader application.
# It installs the necessary Python packages and dependencies.

get_home() {
  local result; result="$(getent passwd "$1")" || return
  echo $result | cut -d : -f 6
}

user_home="$(get_home "$USER")"
sudo mkdir -p "$user_home/.local/share/applications"
sudo chown -R "$USER:$USER" "$user_home/.local/share/applications"
cp -f "hcs_ad_tool.desktop" "$user_home/.local/share/applications/"

sudo apt install python3 python3-tk python3-pip -y
pip3 install --upgrade pip
pip3 install -r requirements.txt
if [ $? -ne 0 ]; then
    echo "Failed to install required packages."
    exit 1
fi
echo "Environment setup completed successfully."
# Ensure the script is executable

echo "Setting up launcher script..."

sudo mkdir -p "/opt/hcs_ad_tool"
sudo cp -f "horizon.png" "/usr/share/pixmaps/horizon.png"
echo "Launcher script setup completed successfully."

# Create a symbolic link to the script in /usr/local/bin
